USE [zhichkin]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[relations](
	[property] [uniqueidentifier] NOT NULL,
	[entity] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_relations] PRIMARY KEY CLUSTERED 
(
	[property] ASC,
	[entity] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

