using System;
using System.Linq;
using System.Collections.Generic;
using System.Data.SqlClient;
using Zhichkin.Metadata.Model;
using Zhichkin.ChangeTracking;
using Zhichkin.Integrator.Model;

namespace Zhichkin.Integrator.Translator
{
    public sealed class ChangeTrackingRecordToSqlCommandAdapter : IMessageAdapter<ChangeTrackingRecord, SqlCommand>
    {
        private Subscription subscription = null;
        private ChangeTrackingRecord adaptee = null;
        private Dictionary<string, string> commands = null;
        private Dictionary<string, object> defaults = null;
        public ChangeTrackingRecordToSqlCommandAdapter() { }
        public IMessageAdapter<ChangeTrackingRecord, SqlCommand> Use(Subscription subscription)
        {
            if (subscription == null) throw new ArgumentNullException("subscription");
            this.subscription = subscription;
            return this;
        }
        public IMessageAdapter<ChangeTrackingRecord, SqlCommand> Input(ChangeTrackingRecord adaptee)
        {
            if (subscription == null) throw new ArgumentNullException("subscription");
            if (adaptee == null) throw new ArgumentNullException("adaptee");
            this.adaptee = adaptee;
            return this;
        }
        public void Output(SqlCommand target)
        {
            if (subscription == null) throw new ArgumentNullException("subscription");
            if (adaptee == null) throw new ArgumentNullException("adaptee");
            if (target == null) throw new ArgumentNullException("target");
            if (defaults == null) InitializeDefaultValues();
            if (commands == null) InitializeSQLCommands();
            target.CommandText = commands[adaptee.SYS_CHANGE_OPERATION];
            target.Parameters.Clear();
            foreach (ChangeTrackingField field in adaptee.Fields)
            {
                target.Parameters.AddWithValue(field.Name, field.Value);
            }
            foreach (KeyValuePair<string, object> item in defaults)
            {
                // not null fields which are not included into translation rules
                target.Parameters.AddWithValue(item.Key, item.Value);
            }
        }
        private void InitializeSQLCommands()
        {
            commands = new Dictionary<string, string>()
            {
                { "I", string.Empty },
                { "U", string.Empty },
                { "D", string.Empty }
            };
            Table table = subscription.Subscriber.MainTable;
            BuildInsertCommand(table);
            BuildUpdateCommand(table);
            BuildDeleteCommand(table);
        }
        private bool IsAutoGeneratedValue(Field field)
        {
            return (field.TypeName == "timestamp" || field.TypeName == "rowversion");
        }
        private object GetDefaultValue(Field field)
        {
            if (field.TypeName == "bigint"
                || field.TypeName == "numeric"
                || field.TypeName == "bit"
                || field.TypeName == "smallint"
                || field.TypeName == "decimal"
                || field.TypeName == "smallmoney"
                || field.TypeName == "int"
                || field.TypeName == "tinyint"
                || field.TypeName == "money")
            {
                return 0;
            }
            else if (field.TypeName == "float"
                || field.TypeName == "real")
            {
                return 0D;
            }
            else if (field.TypeName == "datetime"
                || field.TypeName == "date"
                || field.TypeName == "time"
                || field.TypeName == "datetime2"
                || field.TypeName == "smalldatetime"
                || field.TypeName == "datetimeoffset")
            {
                return new DateTime(1980, 1, 1);
            }
            else if (field.TypeName == "char"
                || field.TypeName == "varchar"
                || field.TypeName == "nchar"
                || field.TypeName == "nvarchar"
                || field.TypeName == "text"
                || field.TypeName == "ntext")
            {
                return string.Empty;
            }
            else if (field.TypeName == "binary")
            {
                return new byte[field.Length];
            }
            else if (field.TypeName == "varbinary"
                || field.TypeName == "image")
            {
                return Guid.Empty.ToByteArray();
            }
            else if (field.TypeName == "timestamp"
                || field.TypeName == "rowversion")
            {
                return null; // the value is auto generated by database engine
            }
            else if (field.TypeName == "uniqueidentifier")
            {
                return Guid.Empty;
            }
            else
            {
                return null;
            }
        }
        private void InitializeDefaultValues()
        {
            defaults = new Dictionary<string, object>();
            foreach (Property property in subscription.Subscriber.Properties)
            {
                if (subscription.TranslationRules.Where((i) => i.TargetProperty == property).FirstOrDefault() == null)
                {
                    foreach (Field field in property.Fields)
                    {
                        if (field.IsNullable) continue;
                        if (IsAutoGeneratedValue(field)) continue;
                        defaults.Add(field.Name, GetDefaultValue(field));
                    }
                }
            }
        }
        private void BuildInsertCommand(Table target)
        {
            string insertSQL = "INSERT {0} ({1}) VALUES ({2})";
            string fields = string.Empty;
            string values = string.Empty;
            string table = target.FullName;
            foreach (TranslationRule rule in subscription.TranslationRules)
            {
                foreach (Field field in rule.TargetProperty.Fields)
                {
                    fields += (fields == string.Empty ? string.Empty : ", ") + string.Format("[{0}]", field.Name);
                    values += (values == string.Empty ? string.Empty : ", ") + string.Format("@{0}", field.Name);
                }
            }
            foreach (KeyValuePair<string, object> rule in defaults)
            {
                string field_name = rule.Key;
                fields += (fields == string.Empty ? string.Empty : ", ") + string.Format("[{0}]", field_name);
                values += (values == string.Empty ? string.Empty : ", ") + string.Format("@{0}", field_name);
            }
            commands["I"] = string.Format(insertSQL, table, fields, values);
        }
        private void BuildUpdateCommand(Table target)
        {
            string updateSQL = "UPDATE {0} SET {1} WHERE {2}";
            string key_value_pairs = string.Empty;
            string field_value_pairs = string.Empty;
            string table = target.FullName;
            foreach (TranslationRule rule in subscription.TranslationRules)
            {
                foreach (Field field in rule.TargetProperty.Fields)
                {
                    if (rule.IsSyncKey)
                    {
                        key_value_pairs += (key_value_pairs == string.Empty ? string.Empty : " AND ") + string.Format("[{0}] = @{0}", field.Name);
                    }
                    else
                    {
                        field_value_pairs += (field_value_pairs == string.Empty ? string.Empty : ", ") + string.Format("[{0}] = @{0}", field.Name);
                    }
                }
            }
            foreach (KeyValuePair<string, object> rule in defaults)
            {
                string field_name = rule.Key;
                field_value_pairs += (field_value_pairs == string.Empty ? string.Empty : ", ") + string.Format("[{0}] = @{0}", field_name);
            }
            commands["U"] = string.Format(updateSQL, table, field_value_pairs, key_value_pairs);
        }
        private void BuildDeleteCommand(Table target)
        {
            string deleteSQL = "DELETE {0} WHERE {1}";
            string key_value_pairs = string.Empty;
            string table = target.FullName;
            foreach (TranslationRule rule in subscription.TranslationRules)
            {
                if (!rule.IsSyncKey) continue;
                foreach (Field field in rule.TargetProperty.Fields)
                {
                    key_value_pairs += (key_value_pairs == string.Empty ? string.Empty : " AND ") + string.Format("[{0}] = @{0}", field.Name);
                }
            }
            commands["D"] = string.Format(deleteSQL, table, key_value_pairs);
        }
    }
}
